### ISSUE TITLE
Enhancement: RSS Feed

### ISSUE THREAD

**Issue by tw2113** [LeaVerou/lea.verou.me#13]
It's the oldschool in me, but does one really have a blog if they don't also have an RSS feed for the blog?

Would love to keep up with your content via RSS feed.

**Comment by LeaVerou** [comment]
Hey all, I just added an Atom feed, please make sure it works well?

**Comment by valtlai** [comment]
It works very well. Maybe a redirect from the old URL `/feed/` should be added?

**Comment by LeaVerou** [comment]
> It works very well. Maybe a redirect from the old URL `/feed/` should be added?

Ooh great idea, thanks! Done!
