### ISSUE TITLE
Bug: [a11y] Page header should observe Reduced Motion

### ISSUE THREAD

**Issue by BenDMyers** [LeaVerou/lea.verou.me#17]
The spinning effect on the page header is neat! However, I keep my computer in Reduced Motion, and I noticed the header background still spins. This could be pretty dizzying for people with vestibular disorders.

Would you be willing to turn off the animation when `prefers-reduced-motion` is set, or maybe use a [no-motion-first](https://www.tatianamac.com/posts/prefers-reduced-motion/) approach?

**Comment by LeaVerou** [comment]
Should be fixed now, thanks!
