### ISSUE TITLE
Feed regression: Migrating Disqus from WP to 11ty

### ISSUE THREAD

**Issue by joyously** [LeaVerou/lea.verou.me#18]
### Page URL:

https://lea.verou.me/blog/2023/preserve-disqus/

### Did this page work in the previous website?

Yes

### Description of issues

One of the consequences of your migration from WordPress to 11ty is that the feed  was not seamless. I got ~230 posts in my feed reader, which was all the history of the feed instead of just the ones since I subscribed 2 years ago.
WordPress has a database field for `guid` which it uses to produce the feed without duplicating posts, even if you move your site. Apparently you used the URL, which has changed (however slightly) so existing feed readers got duplicates.

**Comment by LeaVerou** [comment]
Would it fix that if I output the old URL for old posts?

**Comment by LeaVerou** [comment]
Hey, if you get a chance please let me know if this fixes it so I can close the issue!

**Comment by joyously** [comment]
No, I don't think so because it's the `guid` that WordPress uses, not the URL. My feed reader downloaded all the old posts, because it hadn't seen them before...

**Comment by LeaVerou** [comment]
> Apparently you used the URL, which has changed (however slightly) so existing feed readers got duplicates.

This sounded like if the URL did not change (however slightly) then existing feed readers would not get duplicates. 

> No, I don't think so because it's the guid that WordPress uses, not the URL. My feed reader downloaded all the old posts, because it hadn't seen them before...

Is the guid the same as as the wpid discussed [here](https://lea.verou.me/blog/2023/preserve-disqus/)? 
I wonder if I can specify that id for old entries, and use the URL going forwards.

**Comment by joyously** [comment]
What you are calling the wpid, or the post id, is a sequential number that is the index of the post table. The `guid` looks like a URL, but in WP terms, it is "plain", with query parameters instead of pretty permalinks.
The first post might be like `https://example.com/?p=1` and a page like `https://example.com/?page_id=2` so that the feed can distinguish between posts and pages.
So, yes, I think you can check in your exported data to see the format used, and generate that for old posts. It will only affect those subscribers that haven't checked your feed since your migration (the rest of us have already gotten all the old content again and now have both references).

**Comment by LeaVerou** [comment]
Just pushed another attempt! Hopefully that does it!

**Comment by joyously** [comment]
Today my feed reader downloaded almost all the posts again, so I don't quite understand what it's doing.
Oh, I see that the ones since I subscribed (Nov 2021) and had not deleted, have a different date than the ones that were downloaded today. The ones downloaded today have the date as a day before the ones that I already had.
![Screenshot_2023-07-25_09-50-28](https://github.com/LeaVerou/lea.verou.me/assets/7957680/844969a2-1663-4567-a56f-9f953bd5df8a)

**Comment by LeaVerou** [comment]
😭😭😭

Timezones strike again

**Comment by LeaVerou** [comment]
I think I should probably give up at this point and accept that people will have duplicates just this once, otherwise I risk causing them even more duplicates every time I experiment with ideas about solving the issue. 😞
