### ISSUE TITLE
Bug: Drafts show up in previous/next post

### ISSUE THREAD

**Issue by TomMalbran** [LeaVerou/lea.verou.me#24]
In the footer of the [latest post](https://lea.verou.me/blog/2023/design-state-of-html/) the link to the previews post, links to a [drafted post](https://lea.verou.me/blog/2023/self-closing-defense/).

**Comment by LeaVerou** [comment]
Whoops! Removed the draft post for now (it was accidentally committed anyway), before I solve this properly. Thanks!!
