### ISSUE TITLE
Page regression: Refresh CSS Bookmarklet v2

### ISSUE THREAD

**Issue by loikein** [LeaVerou/lea.verou.me#31]
### Page URL:

https://lea.verou.me/blog/2018/09/refresh-css-bookmarklet-v2/

### Did this page work in the previous website?

Yes

### What issues do you see?

Broken URLs

### Description of issues

Hi,

It seems that the `[Refresh CSS]` button by the end of post is shown in plain code instead of a button.

New version:

<img width="1094" alt="image" src="https://github.com/LeaVerou/lea.verou.me/assets/20618587/c64bedc5-8dd7-49ee-987e-069fe35470c8">

Old version:

<img width="836" alt="image" src="https://github.com/LeaVerou/lea.verou.me/assets/20618587/06fd2602-1fa4-4bf3-ada3-d3d375dc011f">

P.s. I saw no problem with the other two bookmarklet posts.

**Comment by LeaVerou** [comment]
Took almost a year to get to it but it should be fixed now, thanks!
