### ISSUE TITLE
Broken page: Minimalist Affordances: Making the right tradeoffs

### ISSUE THREAD

**Issue by angelod1as** [LeaVerou/lea.verou.me#41]
### Page URL:

https://lea.verou.me/blog/2023/minimalist-affordances/

### Did this page work in the previous website?

Yes

### What issues do you see?

Other

### Description of issues

"Broken Markdown" would be the issue I see. The link inside the image caption does not work.

![image](https://github.com/LeaVerou/lea.verou.me/assets/13950513/1258e061-8730-409a-8ce8-b800fe90e9d6)

(also, the "replace `/blog/` and `lea.verou.me` in GH leads me to a 404)

**Comment by LeaVerou** [comment]
Fixed, thank you!
