### ISSUE TITLE
Broken page: Projects / Stretchy

### ISSUE THREAD

**Issue by drobin04** [LeaVerou/lea.verou.me#45]
### Page URL:

https://lea.verou.me/projects/

### Did this page work in the previous website?

Yes

### What issues do you see?

Broken URLs

### Description of issues

You recently removed an old index.html page on the Stretchy repo, as some files had moved and the page was not loading properly. 

This has caused the direct link to that page from https://lea.verou.me/projects/ to break. 

I'm sure the fix is to update data/projects.json

**Comment by LeaVerou** [comment]
Ah, I just need to update the URL to https://stretchy.verou.me/ 
Thanks!
