### ISSUE TITLE
Page regression: Missing page

### ISSUE THREAD

**Issue by danxxcruz** [LeaVerou/lea.verou.me#53]
### Page URL:

https://lea.verou.me/chainvas

### Old URL:

https://lea0.verou.me/chainvas

### Did this page work in the previous website?

Yes

### What issues do you see?

Other

### Description of issues

Page not found
![Screenshot 2024-03-25 at 14-08-21 Page Not Found • Lea Verou](https://github.com/LeaVerou/lea.verou.me/assets/93965387/6d39d9b1-2e1d-4cc1-a4cd-f3a0bc064056)

**Comment by DmitrySharabin** [comment]
The URL is fixed
