### ISSUE TITLE
Broken page: Help the community: report browser bugs

### ISSUE THREAD

**Issue by AlanORB** [LeaVerou/lea.verou.me#62]
### Page URL:

https://lea.verou.me/blog/2011/09/help-the-community-report-browser-bugs/

### Old URL:

https://lea0.verou.me/2011/09/help-the-community-report-browser-bugs/

### Did this page work in the previous website?

Yes

### What issues do you see?

Broken URLs

### Description of issues

Hello, when tried to access the Smashing Magazine article, I found a 404.

**Comment by LeaVerou** [comment]
Fixed, thanks!
