### ISSUE TITLE
Broken page: Beveled corners & negative border-radius with CSS3 gradients

### ISSUE THREAD

**Issue by 17twenty** [LeaVerou/lea.verou.me#66]
### Page URL:

https://lea.verou.me/blog/2011/03/beveled-corners-negative-border-radius-with-css3-gradients/

### Old URL:

https://lea0.verou.me/2011/03/beveled-corners-negative-border-radius-with-css3-gradients/

### Did this page work in the previous website?

Yes

### What issues do you see?

Broken embed(s)

### Description of issues

Broken

**Comment by LeaVerou** [comment]
Thanks for the report! It looks like this was broken in the previous website too, but you said it works there. Are you seeing something diferent?
