### ISSUE TITLE
Broken page: On compliance vs readability: Generating text colors with CSS

### ISSUE THREAD

**Issue by danielweck** [LeaVerou/lea.verou.me#70]
### Page URL:

https://lea.verou.me/blog/2024/contrast-color/

### Old URL:

https://lea0.verou.me/2024/contrast-color/

### Did this page work in the previous website?

Yes

### Description of issues

Hello Lea, unfortunately a Chromium update somewhere in v130 broke the CSS functionality!

Currently your demo (see screenshot below) works fine in Google Chrome (v129) but fails in Canary (v131) and in fact fails from Electron v33-beta5 onwards (jump from Chromium `130.0.6723.6` to `130.0.6723.19`). I see some changes in the commit log that might explain the regressions, but I don't have time to investigate deeper:
https://chromium.googlesource.com/chromium/src/+log/130.0.6723.6..130.0.6723.19?n=10000&pretty=fuller

Demo links, to compare Google Chrome  Stable vs. Canary:

https://lea.verou.me/blog/2024/contrast-color/

https://codepen.io/leaverou/pen/ExzVOME

<img width="847" alt="Screenshot 2024-10-03 at 02 17 57" src="https://github.com/user-attachments/assets/20cb74ec-3fb3-481d-8c3b-cc8983b275b3">

**Comment by danielweck** [comment]
I narrowed the problem down to some broken parsing of the clamped `l` in this case:

`color: oklch(from rgb(R, G, B) clamp(0, (0.7 / l - 1) * infinity, 1) c h);`

... or `y` in the other technique:

`color: color(from rgb(R, G, B) xyz-d65 clamp(0, (0.36 / y - 1) * infinity, 1) clamp(0, (0.36 / y - 1) * infinity, 1) clamp(0, (0.36 / y - 1) * infinity, 1));`

(please ignore the inclusion of the clamps directly in the `color` expressions, which in your demo are conveniently factored-out as CSS properties ... I needed to do this to work around another Chromium bug present in earlier revisions! ;)

**Comment by doeixd** [comment]
Is there a fix for this?

**Comment by danielweck** [comment]
This Chromium regression bug is difficult to pin-point without introspecting the internals of the CSS calc() computations (which is where I think the failure resides, at least that's where I narrowed it down during my repro tests). I can quite easily make the entire webview crash in Chromium Canary (Chrome Stable works fine with the exact same syntax).

Anyway, I've spent too much time investigating this problem, so I've now decided to downgrade to a basic luminance calculation (I don't strictly need a pure-CSS solution so I used JavaScript to precalculate foreground colours based on the input background).

I'll be watching this space with great interest though, as ideally I would prefer to use a pure-CSS technique.

**Comment by LeaVerou** [comment]
Wow, thanks for catching this! Has this regression been reported as a chromium bug?

**Comment by danielweck** [comment]
I haven't reported it yet, because I am not sure which exact revision of Chromium v130 broke, and I do not have a minimal repro to offer.

**Comment by LeaVerou** [comment]
@DmitrySharabin tracked this down and reported it here: https://issues.chromium.org/issues/371224775

**Comment by danielweck** [comment]
great, thank you.
I did notice that the position of the L channel was a factor, in some cases the web view completely died and had to be reloaded (100% repro, not random). otherwise it was like the calculation just failed internally, but returned a value nonetheless.

**Comment by LeaVerou** [comment]
Meanwhile, there's a very easy fix: invert the calculation so you don't need to divide by `l`. So instead of:

```css
--l-threshold: 0.7;
--l: clamp(0, (var(--l-threshold) / l - 1) * infinity, 1);
color: oklch(from var(--color) var(--l) 0 h);
```

Do:

```css
--l-threshold: 0.7;
--l: clamp(0, (l / var(--l-threshold) - 1) * -infinity, 1);
color: oklch(from var(--color) var(--l) 0 h);
```

I'll edit the article soon (PRs welcome too).
