### ISSUE TITLE
The watch mode is broken

### ISSUE THREAD

**Issue by DmitrySharabin** [LeaVerou/lea.verou.me#81]
This issue seems related to how Eleventy finds dependencies to track in the watch mode, specifically the ones loaded with [import attributes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import/with). I filed an [issue](https://github.com/11ty/eleventy-dependency-tree-esm/issues/4) in the corresponding repo to track the progress. Meanwhile, there is a [workaround](https://github.com/11ty/eleventy/issues/3128#issuecomment-1878745864) we can already apply: use `require` in ESM.

**Comment by LeaVerou** [comment]
Can't we just use `fetch()`?

**Comment by DmitrySharabin** [comment]
> Can't we just use `fetch()`?

It seems to me that in that case, Eleventy would not treat the fetched file as a dependency and would not monitor changes inside it. I still need to check it, though.

**Comment by LeaVerou** [comment]
Okay, I'm fine with createRequire too. Anything that fixes the issue!

**Comment by DmitrySharabin** [comment]
> Okay, I'm fine with createRequire too. Anything that fixes the issue!

Here is the fix, then: https://github.com/LeaVerou/lea.verou.me/pull/82 🙂
